<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-53EJ0K8" failures="3" tests="4" name="Test" time="0.559" errors="0" timestamp="2023-10-23T06:06:49 IST">
  <testcase classname="ins.aiite.TestNGFails.SampleClass9" name="test1" time="0.031">
    <failure type="java.lang.AssertionError" message="expected [TestNG Session Day 1] but found [ Session Day 1]">
      <![CDATA[java.lang.AssertionError: expected [TestNG Session Day 1] but found [ Session Day 1]
at ins.aiite.TestNGFails.SampleClass9.test1(SampleClass9.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="ins.aiite.TestNGFails.SampleClass9" name="test1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [TestNG Session Day 1] but found [ Session Day 1]">
      <![CDATA[java.lang.AssertionError: expected [TestNG Session Day 1] but found [ Session Day 1]
at ins.aiite.TestNGFails.SampleClass9.test1(SampleClass9.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="ins.aiite.TestNGFails.SampleClass9" name="test1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [TestNG Session Day 1] but found [ Session Day 1]">
      <![CDATA[java.lang.AssertionError: expected [TestNG Session Day 1] but found [ Session Day 1]
at ins.aiite.TestNGFails.SampleClass9.test1(SampleClass9.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="ins.aiite.TestNGFails.SampleClass9" name="test2" time="0.02"/>
  <testcase classname="ins.aiite.TestNGFails.SampleClass9" name="test3" time="0.0">
    <ignored/>
  </testcase> <!-- test3 -->
</testsuite> <!-- Test -->
